server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Backend API
    location /api/ {
        proxy_pass https://server-rajdhaniserver-dbitqs-9932f2-62-84-177-235.sslip.io;

        proxy_ssl_server_name on;
        proxy_set_header Host server-rajdhaniserver-dbitqs-9932f2-62-84-177-235.sslip.io;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # React / Vite SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static assets cache
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Prevent hidden files
    location ~ /\. {
        deny all;
    }
}